### ISSUE TITLE
How to start charging over API if eCharger is set to "Auth"

### ISSUE THREAD

**Issue by eingemaischt** [goecharger/go-eCharger-API-v2#218]
I want the charger to not automatically start charging. So I configured it to closed mode.

My old v2 started charging if I set "allow_charging" / alw to 1.

My new Gemini does...nothing. I have to allow charging via app first. Setting allow_charging to 0 works, though.

**Comment by mailb84** [comment]
wie setzt du die Farben der LEDs über die API? Immer wenn ich dies versuche bekomme ich die Fehlermeldung "cch: tried to set api key with invalid json EmptyInput ()"

**Comment by erxbout** [comment]
You could achieve the start of charging by changing the mode to basic?
This would be the api-key "lmo" (logic mode) to 3

For debugging you can check modelStatus where u get a reason why charging is allowed/disallowed at that moment

**Comment by 0xFEEDC0DE64** [comment]
if authentication is set to required, a transaction has to be started to allow the car to charge, use trx=0 for example to start the transaction. The transaction is automatically cleared once the car is disconnected

**Comment by 0xFEEDC0DE64** [comment]
force state is only considered after the authentication is either disabled, or enabled and authenticated.
When authentication is required but currently not authenticated, the algorithm exits out with not charging and the force state is not considered anymore.
So force state will only help when authentication is off or you already authenticated in some way (rfid card or trx=0)

**Comment by phreaks** [comment]
Thx @0xFEEDC0DE64 for your detailed answer. A decision tree is not neccessary :)  ... and it works exactly as you described.

**Comment by unnamed0ne** [comment]
My charger is also configured to require authentication. To enable charging via MQTT you have to authorize an RFID slot.

Here's my home assistant yaml automation as a reference. If you don't use home assistant, you will understand it anyway (replace xxxxxx with the serial number of your charger). And of course you have to disable MQTT rradonly:
```
alias: Wallbox - Unlock for charging
description: >-
  Triggered by the charger entering WaitCar state (cable plugged in).
  Waits for HA to confirm the car is at home (handles GPS delay),
  then waits 10s for the car handshake before authorizing the session.

triggers:
  # WaitCar is the most reliable signal: it comes directly from the
  # charger the moment it detects a cable, regardless of GPS or app state.
  - alias: Charger detects cable (WaitCar state)
    trigger: state
    entity_id: sensor.go_echarger_xxxxxx_car_state
    to: "WaitCar"

conditions: []

actions:
  # Wait until HA confirms the car is at home.
  # If the car is already home, this passes immediately.
  # If GPS is delayed, this waits up to 10 minutes.
  # If the car never arrives (someone else plugged in), abort cleanly.
  - alias: Wait for car to be confirmed at home
    wait_for_trigger:
      - trigger: state
        entity_id: device_tracker.car_location
        to: home
    timeout:
      minutes: 10
    continue_on_timeout: false

  # Allow 15s for the handshake between charger and car.
  # Observed in practice: trx is accepted reliably after ~10s.
  - alias: Wait for car handshake to complete
    delay:
      seconds: 15

  # Authorize RFID slot 1 for this session.
  # Required because charger is configured with ust=1 (auth mode).
  # This simulates an RFID tap without physical interaction.
  - alias: Authorize RFID slot 1 for session
    action: mqtt.publish
    data:
      topic: go-eCharger/xxxxxx/trx/set
      payload: "1"

  # Set force state to neutral (0 = automatic mode).
  # With trx authorized and a car connected, alw becomes true
  # and the charger starts charging.
  - alias: Set force state to neutral
    action: mqtt.publish
    data:
      topic: go-eCharger/xxxxxx/frc/set
      payload: "0"

# Single mode: ignore any re-triggers while the automation is running.
# Prevents double execution if WaitCar fires multiple times.
mode: single
```
