### ISSUE TITLE
Home Assistant auto discovery

### ISSUE THREAD

**Issue by Rothammel** [goecharger/go-eCharger-API-v2#67]
ich würde Home Assistant MQTT V3 auto discovery topics begrüßen.

https://www.home-assistant.io/docs/mqtt/discovery/

**Comment by syssi** [comment]
@Rothammel Bis sich der Hersteller die Mühe gemacht hat jeden einzelnen Sensorwert sauber für das Auto-Discovery zu beschreiben, möchte ich auf meine Custom-Component aufmerksam machen: https://github.com/syssi/homeassistant-goecharger-mqtt

**Comment by 0xFEEDC0DE64** [comment]
Ich habe damals vor längerer Zeit versucht, die http-api vom go-e charger ordentlich in homeassistant zu integrieren, leider fehlte mir schlussendlich die zeit und beim pull-request haben die alle möglichen requirements aufgestellt, von denen ich anfangs nichts wusste.
Falls wer homeassistant von source "bauen" und ausführen möchte, hier ist mein fork noch zu haben:
https://github.com/0xFEEDC0DE64/homeassistant-core

**Comment by ahochsteger** [comment]
@Rothammel, @syssi, @0xFEEDC0DE64, vielleicht ist das für euch von Interesse:
https://github.com/joscha82/wattpilot/pull/9

**Comment by Rothammel** [comment]
wow, sehr gut.
mir persönlich würde:
- amp/set
- att/set
fehlen.
was ich noch verwende ist der /car Status, das ist aber eine number und muss dann sowieso umgemapt werden

**Comment by erxbout** [comment]
Den carstate mappen wir:
![grafik](https://github.com/goecharger/go-eCharger-API-v2/assets/68945126/09ae090a-c150-44c5-93e0-07af21ed0171)

amp set: (also change auf das entity in homeassistant müsste das normal triggern)
![grafik](https://github.com/goecharger/go-eCharger-API-v2/assets/68945126/fe9e4833-2377-45fa-aa34-8b502041e00f)

Ich weiß nicht ob att zu spezifisch ist zum noch dazuschmeißen..
Aber das wäre durch eine automatisierung relativ leicht machbar..
In homeassistant einen helper mit dem entsprechenden wert und wenn dieser sich ändert dann aufs mqtt damit:

``` yaml
alias: Set_Goecharger_ATT
description: ""
trigger:
  - platform: state
    entity_id:
      - input_number.<thecreatedhelper>
    for:
      hours: 0
      minutes: 0
      seconds: 10
condition: []
action:
  - service: mqtt.publish
    data:
      qos: "0"
      topic: goecharger/att/set
      payload: "{{ states('input_number.<thecreatedhelper>') | int }}"
  - service: mqtt.publish
    data:
      qos: "1"
      topic: BalkonyMKII/TARGETOVR
      payload: "{{ states('input_number.<thecreatedhelper>') | int }}"
mode: single

```
